name: ci-api-gateway

on: 
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      content: read
    
    steps:
      - name: checkout
        uses: actions/checkout@5   
