name: ci-api-gateway

on: 
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 17
          cache: maven
        
      - name: maven - compile build test
        run: mvn verify --no-transfer-progress

      - name: sonarqube - SAST + code quality
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        args: >
          -Dsonar.organization=${{ var.SONAR_ORG }}
          -Dsonar.projectKey=${{ var.SONAR_PROJECT_KEY_BACKEND }}
