name: ci-api-gateway

on: 
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 17
          cache: maven
        
      - name: maven - compile build test
        run: mvn verify --no-transfer-progress

      - name: sonarqube - SAST + code quality
        uses: SonarSource/sonarqube-scan-action@da4450e400cebf84292b12a85d4ca0080ae2938c
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        with:
          args: >
            -Dsonar.organization=${{ vars.SONAR_ORG }}
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY_API_GATEWAY }}
